site_name: Render Manager
nav:
- Home: index.md
- Overview: overview.md
- Setup: setup.md
- Documentation: documentation.md
- Maintenance: maintenance.md
- Licence: licence.md
- Roadmap: roadmap.md

theme: 'material'